repos:
  - repo: local
    hooks:
      - id: poetry-export
        name: Export dependencies with Poetry
        entry: poetry export -f requirements.txt --output requirements.txt
        language: system
        files: pyproject\.toml$
        pass_filenames: false