name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  python-job:
    uses: EreminAnton/re-usable-ci/.github/workflows/python-workflow.yml@main
    with:
      python-version: "3.10"
      aws-default-region: "eu-central-1"
      working-directory: "functions"
      dependency-file: "Pipfile"


  terraform-job:
    uses: EreminAnton/re-usable-ci/.github/workflows/terraform-workflow.yml@main
    with:
      terraform-version: "1.4.4"
      aws-default-region: "eu-central-1"