name: 'base'

on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-job:
    uses: fivexl/github-reusable-workflows/.github/workflows/python-job.yml@main
    with:
      python-version: "3.10"
      aws-default-region: "eu-central-1"
      working-directory: "functions"

  terraform-job:
    uses: fivexl/github-reusable-workflows/.github/workflows/terraform-job.yml@main
    with:
      terraform-version: "1.5.0"
      aws-default-region: "eu-central-1"
